name: Generate Snake

on:
  # run manually or every day at 00:00 UTC
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

# ── NEW: give the token write access so Pages can push ──
permissions:
  contents: write        # REQUIRED for crazy‑max/ghaction‑github‑pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Generate the SVG (svg‑only flavor = faster, no video)
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3           # ← svg-only !
        with:
          github_user_name: awnishprasad99
          outputs: |
            dist/github-contribution-grid-snake.svg

      # 2️⃣ Push SVG to the branch `output`
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output                 # branch will be auto‑created
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
